name: atmonitor
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Asus pc <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  firebase:
  firebase_dart_ui: ^0.1.1
  csv: ^4.0.1

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
